config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  resources :restaurants do
    resources :reviews, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORY }
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  RATING = [0, 1, 2, 3, 4, 5]
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(reviews_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant), status: :see_other
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for (restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :category , collection: Restaurant::CATEGORY %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/index.html.erb
<div class='container'>

  <h1>Restaurants</h1>

  <% @restaurants.each do |restaurant| %>
    <p><%= restaurant.name%> <%= link_to "See Details", restaurant_path(restaurant.id), class: "btn btn-primary"%></p>
    <br>
  <% end %>
  <%= link_to 'Add a new restaurant', new_restaurant_path, class: "btn btn-primary"%>
</div>

app/views/restaurants/new.html.erb
<div class='container'>
<h1>New restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back to list', restaurants_path, class: "btn btn-primary"%>

</div>

app/views/restaurants/show.html.erb
<div class='container'>

  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.category.upcase %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>

  <p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>
<br>

  <%=  render 'reviews/form', restaurant: @restaurant, review: @review%>

  <%= link_to 'Back to list', restaurants_path, class: "btn btn-primary"%>

</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.input :rating, collection: 0..5%>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/new.html.erb
<div class='container'>
<h1>Add a review</h1>

<%= render 'form', review: @review %>

  <%= link_to 'Back to restaurant', restaurant_path(@restaurant), class: "btn btn-primary"%>

</div>